PYTHONPATH="/notebooks/tensorflow/mingqiu/NTIRECompetition"
export PYTHONPATH
python3 trainDWT_avdh.py  --groundtruthdir=data/DIV2K_2018/augmentation/DIV2K_train_HR \
                     --datadir=data/DIV2K_2018/augmentation/DIV2K_train_LR_x8 \
                     --valid_datadir=data/DIV2K_2018/DIV2K_valid_LR_x8 \
                     --valid_groundtruthdir=data/DIV2K/DIV2K_valid_HR \
                     --postfixlen=2 \
                     --validpostfixlen=2 \
                     --waveletimgsize=100 \
                     --imgsize=100 \
                     --wavelet=db1 \
                     --scale=8 \
                     --layers=64 \
                     --featuresize=256 \
                     --batchsize=4 \
                     --savedir=ckpt/x8_crop100_layer64_f256_3ch_new \
                     --logdir=x8_crop100_layer64_f256_3ch_log \
                     --reusedir=result/x8_crop100_layer64_f256_3ch_new/x8_crop100_layer64_f256_3ch_new \
                     --reuseep=10000 \
                     --iterations=400000